@server = http://localhost
@port = 3000
@api_path = api
@api_version = 1
@url = {{server}}:{{port}}/{{api_path}}/v{{api_version}}

###############################################

// Test: Get all subjects
// Expected HTTP response status code: 200
// Expected response: an array (json) with all subjects
// [{}, {}, ...]
GET {{url}}/subjects

###############################################

// Test: Get a subject
// Expected HTTP response status code: 200
// Expected response: an json object with the subject
// {"_id": "65815ac4ef1bb098359766c2", "subjectName": "Physics", "subjectCode": "PHY", "description": "Physics studies the properties of matter and energy."}
GET {{url}}/subjects/PHY